targets:
  $default:
    builders:
      needle-factory:
        enabled: true

builders:
  needle-factory:
    target: ":needle"
    import: "package:needle/builder/builder.dart"
    builder_factories: ["factoryBuilder"]
    build_extensions: {".dart": [".needle.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
