name: needle
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5

dev_dependencies:
  build_test: ^1.0.0

