name: needle
description: Needle is a dependency injection library for Dart/Flutter inspired by Autofac ( https://autofac.org/ ).
version: 0.0.1-dev.5
homepage: https://github.com/champeauxr/needle

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.2
  dart_style: ^2.0.1
  glob: ^2.0.1
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  build_test: ^2.1.0

