name: needle
description: Needle is a dependency injection library for Dart/Flutter inspired by AutoFac (https://autofac.org/).
version: 0.0.1-dev.2
homepage: https://github.com/champeauxr/needle

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.39.10
  build: ^1.3.0
  source_gen: ^0.9.5
  dart_style: ^1.3.6
  glob: ^1.2.0
  freezed_annotation: ^0.11.0

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.2
  build_test: ^1.0.0

